// Create class
POST http://localhost:3003/class
Content-Type: application/json

{
  "name": "Cruz",
  "startDate": "2021-01-25",
  "endDate": "2021-08-30",
  "shift": "fulltime",
  "module": 4
}

###

// Create student
POST http://localhost:3003/student
Content-Type: application/json

{
  "name": "Teste",
  "email": "teste@mail.com",
  "birthDate": "2017-02-20"
}

###

// Choose a class to a student
POST http://localhost:3003/student/update-class/8433274f-06df-4876-821b-7fef33afbf44
Content-Type: application/json

{
  "classId": "1f193484-dc32-40dc-a59a-9ba761fea701"
}

###

// Get a student's age
GET http://localhost:3003/student-age/d4fbb9a3-7c9e-4e0b-8077-d4ac5a67020d

###

// Get students by class
GET http://localhost:3003/class/1f193484-dc32-40dc-a59a-9ba761fea701/students

###

// Create specialty
POST http://localhost:3003/teacher/specialty
Content-Type: application/json

{
  "name": "Infra"
}

###

// Create teacher
POST http://localhost:3003/teacher
Content-Type: application/json

{
  "name": "Tom Hanks",
  "email": "tom@mail.com",
  "birthDate": "1960-06-15",
  "specialties": ["0b7f1767-5a0f-45dc-9f77-7f7e7ba848fb"]
}

###

// Assign teacher to a class
PATCH http://localhost:3003/teacher/7430e843-a16a-4db0-aa13-e1a7a530612b
Content-Type: application/json

{
  "classId": "1f193484-dc32-40dc-a59a-9ba761fea701"
}

###

// Get teachers by class
GET http://localhost:3003/class/1f193484-dc32-40dc-a59a-9ba761fea701/teachers

###

// Create hobby
POST http://localhost:3003/student/hobby
Content-Type: application/json

{
  "name": "Sing"
}



